// server/workflows/workflows.ts — the composer workflow catalogue (issue #167).
//
// Workflows are guided, explicit user-invoked actions, distinct from reminders
// (which attach trusted instructions to the next message). Each workflow ships
// a trusted "injector": server-owned instructions appended to the submitted
// prompt when the browser names the workflow by id. Unlike reminder bodies the
// injector text IS exposed over GET /api/workflows — the contract is that the
// user can read the exact trusted content before submitting. Trust comes from
// resolution-by-id at send time (the browser can never author or alter the
// injected text), not from secrecy.

export const WORKFLOW_ID_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
export const WORKFLOW_ID_MAX = 255;

/**
 * The hard ceiling on any workflow argument, whatever a preset declares. The
 * prompt route refuses text longer than 100,000 characters, so a preset must
 * never advertise a field whose full contents the send would then reject.
 */
export const WORKFLOW_ARGUMENT_MAX_LENGTH = 100_000;

/**
 * The single free-text field a workflow collects. Its typed value IS the
 * visible prompt — the same shape "Send an update to another session" and
 * "Launch a Managed Child" already have, generalized so a workflow can be
 * added by describing its field rather than by growing another branch in the
 * dialog.
 *
 * The spec is presentation for a field the browser renders; it grants no
 * authority. Trust still comes from resolving `injector` by id at send time.
 */
export interface WorkflowArgumentSpec {
  label: string;
  placeholder?: string;
  hint?: string;
  required: boolean;
  /** Bounded by WORKFLOW_ARGUMENT_MAX_LENGTH before the catalogue is served. */
  maxLength: number;
}

export interface WorkflowPreset {
  id: string;
  title: string;
  description: string;
  /** Trusted, server-resolved instructions appended to the submitted prompt. */
  injector: string;
  /** Collected free text. When present, what the human types is the prompt. */
  argument?: WorkflowArgumentSpec;
  /** Fixed visible prompt for a workflow that collects nothing at all. */
  prompt?: string;
}

// Catalogue order follows the picker's semantic groups: Review, Coordinate,
// Execute, Investigate, Document, Ship.
const RAW_CATALOGUE: WorkflowPreset[] = [
  {
    id: "playwright-ui-review",
    title: "Review a UI change with Playwright",
    description:
      "Drive a focused Playwright pass over one route or component and bring back targeted evidence, without a full deployment or a complete screenshot regeneration.",
    injector: [
      'You are running the "Review a UI change with Playwright" workflow.',
      "- Start only what this check needs (prefer the dev server or the deterministic mock stack); do not run a full deployment.",
      "- Drive the named route with Playwright and exercise exactly the requested state or interaction.",
      "- Collect evidence for the affected UI only: assertions for an interaction-only scope, plus focused screenshots of the affected area when the scope asks for visual evidence. Never regenerate the complete screenshot set.",
      "- Report what was verified, what failed, and where any evidence was written.",
    ].join("\n"),
  },
  {
    id: "pr-snippet-review",
    title: "Post a snippet-by-snippet PR review",
    description:
      "Walk one pull request as an ordered sequence of explained snippets and post it as a single GitHub comment. Takes only the pull request number; the repository comes from this project directory.",
    injector: [
      'You are running the "Post a snippet-by-snippet PR review" workflow.',
      "Produce ONE GitHub comment that walks a senior engineer through the pull request as a sequence of explained snippets, then post it with `gh pr comment <number> -F -`.",
      "",
      "Gather first:",
      "- Resolve the repository from this session's project directory. NEVER take a repository, owner, or host from the prompt — the only input this workflow accepts is a pull request number.",
      "- Read `gh pr view <n>`, `gh pr diff <n>`, and the changed files themselves. The diff says what moved; the files say what it means.",
      "- Resolve the head SHA (`gh pr view <n> --json headRefOid`) and pin every link to it, so line links cannot drift when the branch moves:",
      "  https://github.com/<owner>/<repo>/blob/<headSha>/<path>#L<start>-L<end>",
      "",
      "Structure:",
      "- Order steps so each one motivates the next. Reading order is NOT file order: begin with the fact or constraint the change rests on, then the mechanism, then its consequences, then the tests.",
      "- Each step is a numbered heading, one to three sentences, a fenced snippet of the ACTUAL code, and a link to the full file.",
      "- Keep every snippet to the smallest excerpt that carries the idea, and quote it exactly — never paraphrase code inside a fence.",
      "- A step may legitimately carry no snippet when it explains an empirical finding or constraint that justifies the next one.",
      "- Explain WHY a non-obvious choice was made, not just what the code does. Where something was a judgement call rather than a fact, say so plainly.",
      "",
      "Close with a short \"where I'd focus your scrutiny\" list naming the riskiest snippet, any judgement calls, and anything the change does NOT verify.",
      "Never claim a test, lane, or verification you did not actually run. If the diff is too large to cover honestly, say so and cover the load-bearing parts rather than silently truncating.",
      "Post exactly one comment. Report the resulting comment URL when you are done.",
    ].join("\n"),
  },
  {
    id: "red-team",
    title: "Red-team the work just produced",
    description:
      "Argue against the plan or diff that was just produced, grounding every objection in evidence and closing with exactly one verdict.",
    argument: {
      label: "Target",
      placeholder: "your most recent output, docs/rfc.md, or the plan above",
      hint: "Name the file or plan to argue against. Say \"your most recent output\" to red-team the work already in this transcript.",
      required: true,
      maxLength: 4_000,
    },
    injector: [
      "Red-team what you just produced. If the note above names a file or a plan, target",
      "that; otherwise target your own most recent output.",
      "",
      "Open with the side-switch, verbatim, as the first line:",
      "",
      "> Red-teaming the work above. I am arguing against it.",
      "",
      "Then:",
      "",
      "1. Work all six objection classes — wrong problem, cheaper alternative, hidden",
      "   coupling, operational cost, reversibility, the unchecked assumption. Say so",
      "   explicitly when a class yields nothing.",
      "2. Ground every objection in `file:line`, pasted command output, or a doc URL.",
      "   Grep for the other callers rather than reasoning about them.",
      "3. Keep objections you cannot ground in a separate, clearly labelled",
      "   speculative bucket. Never mix them with grounded ones.",
      "4. Rank the grounded objections by likelihood x cost-if-true x cheapness-to-check",
      "   and present them as a table.",
      "5. Close with the single cheapest experiment that would kill the work, and a",
      "   verdict of exactly one of `proceed`, `proceed-with-change`, or `stop`.",
      "",
      "Do not re-litigate the work's merits. The case for it has already been made.",
      "Prefer a fresh subtask context for anything larger than a small diff so the",
      "reviewer does not inherit the author's sunk cost.",
      "",
      "Score likelihood, cost if true, and inverted cost-to-check from 1-5; sort by",
      "their product. Cheap checks on plausible expensive failures should rise first.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| Review hedges or praises the work | Re-state the side switch and delete the defense |",
      "| Concerns are plausible but ungrounded | Run the grep/curl/read or move them to speculative |",
      "| Highest concern cannot be acted on | Include cost-to-check and identify one experiment |",
      "| Same blind spot survives | Move the artifact into a fresh subtask context |",
      "| Review ends with concerns but no decision | Emit one of the three exact verdicts |",
    ].join("\n"),
  },
  {
    id: "review-learning",
    title: "Review code with learning excerpts",
    description:
      "Review a diff or pull request findings-first as a senior engineer, then teach from two to five exact, cited source excerpts.",
    argument: {
      label: "Review target",
      placeholder: "the current diff, pull request #253, or server/routes/sessions.ts",
      hint: "Name the diff, pull request, file, or subsystem to review. Nothing is changed, posted, or persisted.",
      required: true,
      maxLength: 4_000,
    },
    injector: [
      "Review the target above as a senior engineer and turn the result into a concise",
      "learning walkthrough. If no target is supplied, review the current diff. Honor",
      "any requested subsystem or boundary first, such as authentication or an",
      "external-runtime integration.",
      "",
      "This procedure is self-contained. Do not load or defer to a skill. Do not change",
      "code, post comments, open issues, or persist the walkthrough unless the user",
      "explicitly asks after the review.",
      "",
      "## Review before teaching",
      "",
      "Inspect the complete diff and enough surrounding code, callers, tests,",
      "configuration, and contracts to understand behavior across layers. For a PR,",
      "review the whole change at its pinned head revision rather than only the latest",
      "commit. Reproduce or run focused checks when safe and feasible.",
      "",
      "Return findings first, ordered by severity. Each finding must contain:",
      "",
      "- severity and a precise title;",
      "- repository-relative `path:line-line` at the defect or risky behavior;",
      "- concrete failure mode and affected user/system;",
      "- evidence establishing the claim;",
      "- the smallest useful remediation direction, without implementing it.",
      "",
      "Separate `Verified findings` from `Unverified risks`. A verified finding is",
      "supported by implementation, a reproducer, test output, or an authoritative",
      "contract. An unverified risk names exactly what evidence is missing and the",
      "cheapest check. Do not inflate educational observations into findings.",
      "",
      "If there are no findings, say that explicitly before teaching and name residual",
      "risks and test gaps. \"No findings\" never means \"proved correct\".",
      "",
      "## Then teach from a small evidence set",
      "",
      "After findings, select two to five high-value excerpts. Choose code that explains",
      "an invariant, boundary, state transition, failure strategy, or non-obvious",
      "tradeoff. Do not quote routine plumbing, the whole diff, or several snippets",
      "that teach the same lesson.",
      "",
      "For every excerpt:",
      "",
      "1. give an exact repository-relative `path:line-line` verified against the",
      "   reviewed revision;",
      "2. quote the smallest contiguous source range that is independently readable;",
      "3. state whether it is `Finding evidence` or `Educational`;",
      "4. explain the engineering lesson and why the implementation shape matters;",
      "5. connect it to the preceding and following layer;",
      "6. state what the excerpt does not prove.",
      "",
      "Use this output shape:",
      "",
      "```text",
      "Verified findings",
      "1. [severity] Title — path:line-line",
      "   Failure, evidence, remediation direction.",
      "",
      "Unverified risks",
      "- Risk — missing evidence; cheapest verification.",
      "",
      "Layer map",
      "HTTP route -> service/pool -> sidecar protocol -> external SDK",
      "",
      "Learning excerpts",
      "1. path:line-line — Finding evidence | Educational",
      "   <minimal exact quote>",
      "   Lesson: ...",
      "   Connection: previous layer -> this code -> next layer.",
      "   Does not prove: ...",
      "",
      "Residual risks and test gaps",
      "- ...",
      "```",
      "",
      "Adapt the layer map to the repository. Distinguish control flow from authority:",
      "a route calling a service does not prove the service may trust browser input,",
      "and a mock sidecar does not prove the external SDK behaves the same way. Keep",
      "quoted lines exact, explanations concise, and educational value subordinate to",
      "the correctness review.",
    ].join("\n"),
  },
  {
    id: "session-update",
    title: "Send an update to another session",
    description:
      "Deliver a hand-off message to another session in this project after an explicit preview of the target and the exact prompt.",
    injector: [
      'You are receiving the "Send an update to another session" workflow.',
      "This message was composed in another session in the same project and delivered here after an explicit preview and confirmation. Treat it as new input from the user's other workstream: read it, reconcile it with your current task, and continue accordingly.",
      "Delivery is asynchronous (POST /session/{id}/prompt_async answers 204 for accepted, not completed), so do not assume the sender is watching this transcript live.",
    ].join("\n"),
  },
  {
    id: "managed-child",
    title: "Launch a Managed Child",
    description:
      "Start an independent child session with its own transcript and a Plan or Build policy fixed at creation time. No native task card is created and no automatic hand-back occurs.",
    injector: [
      'You are a managed child session started by the "Launch a Managed Child" workflow.',
      "- You run in your own independent transcript with the Plan or Build policy fixed at creation time.",
      "- No native task card exists in the parent and no automatic hand-back will occur: the human reads your results here, in this transcript.",
      "- Complete the objective below and end with a clear summary of outcomes, remaining risks, and suggested next steps.",
    ].join("\n"),
  },
  {
    id: "start-dca-session",
    title: "Start a DCA session",
    description:
      "Start an independent root session in this project or an isolated worktree, after reviewing its Plan/Build mode, model, assignment, and trusted instructions.",
    injector: [
      'You are an independent root session started by the "Start a DCA session" workflow.',
      "- You have no parent session, task card, Managed Child relationship, automatic hand-back, or provenance link to the session that started you.",
      "- Work only on the assignment below under the Plan or Build mode selected at launch.",
      "- End with a clear summary of outcomes, verification performed, remaining risks, and suggested next steps.",
    ].join("\n"),
  },
  {
    id: "manager-children",
    title: "Run a wave of manager children",
    description:
      "Dispatch isolated OpenCode workers into sibling git worktrees and manage their status files, branches, and pull request wave.",
    argument: {
      label: "Wave to manage",
      placeholder: "the four independent notification fixes in issues #288, #290, #291, #294",
      hint: "Describe the disjoint assignments. Each child gets its own worktree, branch, and status file.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Manage the work described above through separate OpenCode workers in sibling git",
      "worktrees and unfocused CMUX workspaces.",
      "",
      "Before dispatch:",
      "",
      "1. Write a durable wave plan with ownership, dependencies, integration order,",
      "   and final verification.",
      "2. State explicitly that standalone children continue after this turn but do",
      "   not automatically resume the manager.",
      "3. Create one worktree and branch per disjoint assignment from the current",
      "   remote default branch.",
      "4. Require status files, heartbeats, verified commits, pushed branches, and PRs.",
      "",
      "Standalone children cannot resume this manager by writing status, pushing a PR,",
      "changing a badge, or running `cmux notify`. Those are durable evidence or human",
      "alerts, not an OpenCode callback. The manager resumes only on a user message, an",
      "in-process task result, or a separately tested supervisor prompt. Never promise",
      "unattended progression without that wake channel.",
      "",
      "Cut waves on complete artifacts and disjoint files. Parallel workers may read",
      "shared files but must not edit the same integration file, lockfile, migration,",
      "generated output, port, or database. Cap a wave around five children. Create",
      "each sibling worktree after fetching the remote default branch, verify its path,",
      "branch, clean status, dependencies, baseline, and fixed-port ownership.",
      "",
      "Every cold-start assignment must name the absolute worktree and branch,",
      "objective, owned and forbidden files, sibling workers, settled contracts,",
      "non-goals, permission posture, model, exact tests, definition of done, and the",
      "rule that children never push the default branch. Require a gitignored",
      "`.agent-status.json` with phases `assigned`, `working`, `verifying`, `pushed`,",
      "`pr-open`, `blocked`, and `done`; UTC timestamps come from `date -u`, update on",
      "every transition, and heartbeat at least every ten minutes.",
      "",
      "Before launching, ask the user which model to use when neither the repository",
      "nor the current session has an explicit model contract that settles the choice.",
      "Do not guess from availability, cost, or a previous unrelated child. Never add",
      "`--auto` or any equivalent broad permission-approval mode unless the user",
      "explicitly authorizes it for these workers. A copied launch command is not",
      "authorization. Record both decisions in each assignment and launch command.",
      "",
      "Monitor in this order: status file, Git/remote/PR/CI evidence, then the child",
      "screen only when evidence is stale or contradictory. A stale heartbeat or a",
      "`done` badge without a pushed branch is not delivery proof.",
      "",
      "On every resumed turn, read the durable plan and status files, fetch remotes,",
      "inspect exact-head checks, reconcile ownership, then continue the queued action.",
      "If nothing is ready, report that and stop rather than busy-waiting. Integrate one",
      "reviewed branch at a time, run the full suite after each merge, and clean a",
      "worktree only after merge and after confirming no follow-up needs it.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| Manager stops after dispatch | Wait for a real inbound turn; restore durable state |",
      "| Notification produces no manager action | Correct the claim: it notified a human only |",
      "| Two children edit one seam | Stop one writer and sequence ownership |",
      "| Tracker says done but no PR exists | Inspect Git and require push/PR evidence |",
      "| Child works in the wrong checkout | Stop and relaunch with absolute containment |",
      "| Model was not specified or contractually settled | Ask before launch |",
      "| Launch template contains `--auto` without explicit authorization | Remove it and ask; do not broaden permissions by convenience |",
      "| Automated wake duplicates turns | Disable it until idle checks, dedupe, and serialization are proven |",
      "| Manager loses the next action | Restore the synchronized plan and task queue |",
    ].join("\n"),
  },
  {
    id: "native-worktree-subagents",
    title: "Delegate to native worktree subagents",
    description:
      "Delegate disjoint edits to native Task children confined to a sibling worktree, with fail-closed containment guards before every mutation.",
    argument: {
      label: "Work to delegate",
      placeholder: "the three independent client fixes on this branch",
      hint: "Describe the disjoint edits. Children stay scoped to this session's OpenCode directory regardless of their assigned worktree.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Delegate the work described above only after confirming a fresh Build-only parent and a",
      "dedicated sibling worktree from fresh `origin/main`. A parent that previously",
      "activated Plan may pass historical denies to children even after its own Build",
      "tools return. If the child cannot pass preflight, stop; never weaken policy or",
      "substitute an unrelated root session.",
      "",
      "The child remains scoped to the parent's OpenCode directory. External-directory",
      "permission does not change relative path resolution, shell CWD, LSP/VCS scope,",
      "or event directory. Its cold-start prompt must require:",
      "",
      "1. The absolute worktree path and branch, with edits allowed only there.",
      "2. Every Bash call setting `workdir` there or using `git -C <absolute-path>`.",
      "3. Every read, edit, and patch using an absolute path inside the worktree.",
      "4. Exclusive file ownership, non-goals, exact verification, commit/push rules,",
      "   and the final report.",
      "5. This guard before edits, tests, commit, and push:",
      "",
      "       pwd",
      "       git rev-parse --show-toplevel",
      "       git status --short --branch",
      "",
      "The child must stop without mutation unless both `pwd` and Git top-level equal",
      "the assignment. Never fall back to the parent checkout, force-push, or push the",
      "default branch. Parallel children must not share a lockfile, migration, port,",
      "database, generated artifact, or integration file. Review the diff and checks",
      "at hand-back before presenting or merging it, and never duplicate its work.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| Child resolves paths in the parent checkout | Stop and relaunch with absolute containment rules |",
      "| Tool remains denied in Build | Use a fresh Build-only parent; do not weaken rules |",
      "| Separate branches still conflict | Sequence shared ownership or give it to one owner |",
      "| Hand-back is unclear | Fix the prompt's deliverable and verification contract before launch |",
    ].join("\n"),
  },
  {
    id: "session-handoff",
    title: "Hand off to a standalone session",
    description:
      "Carry the current task into one explicitly configured standalone OpenCode session, with a self-contained packet and explicit CLI flags.",
    argument: {
      label: "Task to hand off",
      placeholder: "finish the epic hierarchy work on feat/planning-epic-hierarchy",
      hint: "Nothing is inherited automatically, so describe the task the way the receiving session will need to read it.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Prepare one standalone OpenCode session for the task described above.",
      "",
      "Nothing is inherited automatically. Carry settings through explicit CLI flags",
      "and a self-contained handoff packet.",
      "",
      "1. Choose the mechanism: fresh interactive TUI for steerable work,",
      "   `opencode run` for scripted work, `--session <id> --fork` only when history",
      "   must be copied, or the task tool when this is actually a subagent job.",
      "2. Inspect `opencode agent list`, `opencode models`, the repository root, branch,",
      "   worktree state, and baseline. Mark anything you cannot verify as UNVERIFIED.",
      "3. Write a prompt file outside the worktree containing the absolute path,",
      "   branch, objective, progress, settled decisions with rationale, owned and",
      "   forbidden files, requested agent/model/variant, permission posture,",
      "   verification commands, stop condition, and unverified assumptions.",
      "4. Show the packet and exact launch command before executing it. Use",
      "   `--agent plan` or `--agent build`; do not express mode as prompt prose.",
      "   Use `--variant` for provider-specific reasoning effort. `--thinking` controls",
      "   display only. Never add `--auto` unless the user explicitly requested it.",
      "5. Keep secrets out of the packet and process arguments. Verify the target",
      "   branch before allowing edits.",
      "6. After launch, verify the working directory, branch, selected agent and model,",
      "   and that the first reply understood the packet. A successful process start",
      "   proves what was requested, not what the provider accepted.",
      "",
      "Use cmux only as an optional presentation wrapper and never steal focus. Store",
      "the packet outside every worktree and keep secrets out of it: prompt text can",
      "surface in shell history or process arguments. Require the child's first reply",
      "to restate its path, branch, objective, ownership, agent, model, variant,",
      "permission posture, and stop condition before work begins.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| Child edits instead of planning | Relaunch with `--agent plan`; prose is not mode control |",
      "| History was copied unexpectedly | Use a fresh TUI or run without continuation/fork flags |",
      "| Child opens the wrong repository | Pass an absolute project path or `--dir` |",
      "| Parent and child overwrite one another | Assign disjoint ownership and stop one writer |",
      "| Secret appears in process arguments | Stop, remove it, and rotate the exposed credential |",
      "| Provider ignores the reasoning variant | Mark acceptance UNVERIFIED until reported |",
      "",
      "After launch, report what started and end the parent turn. Do not begin the",
      "child's assigned work.",
    ].join("\n"),
  },
  {
    id: "goal",
    title: "Complete an objective autonomously",
    description:
      "Work an objective through research, implementation, fixes, and final verification as one sustained run with durable checkpoints.",
    argument: {
      label: "Objective",
      placeholder: "make the notification badge match the server's global unresolved count",
      hint: "The run continues without asking whether to proceed, so state the acceptance criteria you actually want.",
      required: true,
      maxLength: 100_000,
    },
    injector: [
      "Complete the objective above as one sustained run.",
      "",
      "Do not ask whether to continue. Work through research, implementation, fixes,",
      "and final verification until the objective is complete or a real user decision",
      "blocks it.",
      "",
      "Before changing code:",
      "",
      "1. Read repository instructions and inspect the relevant code, tests, current",
      "   branch, and worktree state. Do not overwrite unrelated changes.",
      "2. Translate the objective into acceptance criteria and a task list that",
      "   includes final verification. Record assumptions separately from facts.",
      "3. Create a durable checkpoint using the project's existing status/plan",
      "   convention. If none exists, write a clearly named progress file outside the",
      "   git worktree in a persistent user-state directory, not a temporary directory,",
      "   and report its absolute path. Include the objective, criteria, assumptions,",
      "   current task, completed tasks, touched files, verification, and restart",
      "   instructions. Mirror the active task in the session todo list.",
      "",
      "During the run:",
      "",
      "- Make the best reasonable guess for ambiguous, reversible, non-safety choices.",
      "  Record the guess and rationale in the checkpoint, implement it, and continue.",
      "- Prefer the smallest correct change and established repository conventions.",
      "- Update the checkpoint and todo list after each meaningful boundary, before a",
      "  long operation, and after any verification failure. Keep timestamps in UTC.",
      "- Treat failed checks as work to diagnose and fix, not as a reason to ask whether",
      "  to proceed. Rerun affected checks after each bounded fix.",
      "- Preserve Plan/Build and tool permissions. Never switch modes, alter policy, or",
      "  bypass a permission denial to gain authority the session does not have.",
      "- Obey every confirmation gate. Do not invent credentials, tokens, approvals,",
      "  facts, test results, or access. Never expose secrets in checkpoints or output.",
      "- Ask one focused question only when progress requires a genuinely irreversible",
      "  or destructive action, security/privacy authorization, privilege escalation,",
      "  spending decision, unavailable credential/access grant, or product choice",
      "  whose plausible answers have materially different consequences. State what",
      "  was tried, the exact decision needed, safe options, and what remains preserved.",
      "- Do not turn inconvenience, ordinary ambiguity, or a recoverable test failure",
      "  into a user question. Continue all independent work before declaring blocked.",
      "",
      "At completion, run the repository's relevant focused and broad verification.",
      "Inspect the final diff and status for accidental or unrelated changes. Update",
      "the durable checkpoint to completed or blocked, with exact commands and results.",
      "Report acceptance criteria, changed files, assumptions made, verification,",
      "remaining risks, and any work that exists only locally. Never claim completion",
      "from an accepted asynchronous operation; poll or otherwise verify its outcome.",
    ].join("\n"),
  },
  {
    id: "dca",
    title: "Operate DCA sessions over the BFF API",
    description:
      "Create, prompt, and observe DCA sessions through the agent-facing BFF HTTP API, distinct from the human-only composer workflows.",
    argument: {
      label: "Session work",
      placeholder: "launch a read-only child that audits export error handling and report its findings",
      hint: "Describe the session lifecycle work. The procedure below calls already-authorized BFF endpoints directly.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Use DCA's BFF API for the request above. This is the agent-facing HTTP workflow for",
      "creating, prompting, and observing sessions. It is distinct from DCA's",
      "human-only \"Start a DCA session\" composer workflow: that UI asks a human to",
      "review and launch a session, while this command calls already-authorized BFF",
      "endpoints directly.",
      "",
      "First establish the boundary:",
      "",
      "1. Set `DCA_BASE_URL` to the deployment's canonical BFF origin, without a",
      "   trailing slash. Do not assume `127.0.0.1`, a port, or even that loopback is",
      "   reachable from this shell. A remote, containerized, sandboxed, or phone-side",
      "   shell may need a private DNS/Tailscale URL or may have no route at all.",
      "2. Use the deployment's existing authentication mechanism. The examples below",
      "   omit auth headers; that is valid only for a private deployment that actually",
      "   has no app-level auth. Never invent a token or put a secret in a tracked file.",
      "3. Confirm network access and upstream health before creating anything:",
      "",
      "```bash",
      ": \"${DCA_BASE_URL:?Set DCA_BASE_URL to the reachable DCA BFF origin}\"",
      "curl -sS --fail-with-body \"$DCA_BASE_URL/api/health\" | jq .",
      "```",
      "",
      "`healthy: true` proves the BFF answered. Also inspect `upstream.reachable`,",
      "`upstream.versionMatches`, and `events.connected`; do not flatten those distinct",
      "signals into one claim.",
      "",
      "Use an absolute project path and URL-encode it. List root sessions:",
      "",
      "```bash",
      "PROJECT=/absolute/path/to/project",
      "curl -sS --fail-with-body --get \"$DCA_BASE_URL/api/sessions\" \\",
      "  --data-urlencode \"directory=$PROJECT\" \\",
      "  --data-urlencode \"roots=true\" \\",
      "  --data-urlencode \"limit=50\" | jq .",
      "```",
      "",
      "Create a root and submit its first prompt in one request. `mode` is `plan` or",
      "`build`; the server validates any `model` and optional isolated worktree fields.",
      "",
      "```bash",
      "BODY=$(jq -n \\",
      "  --arg directory \"$PROJECT\" \\",
      "  --arg title \"Investigate flaky export test\" \\",
      "  --arg prompt \"Diagnose the flaky export test. Do not edit files; report evidence.\" \\",
      "  '{directory:$directory,title:$title,prompt:$prompt,mode:\"plan\"}')",
      "CREATED=$(curl -sS --fail-with-body -X POST \"$DCA_BASE_URL/api/sessions\" \\",
      "  -H 'Content-Type: application/json' -d \"$BODY\")",
      "SESSION_ID=$(jq -er '.session.id' <<<\"$CREATED\")",
      "printf '%s\\n' \"$SESSION_ID\"",
      "```",
      "",
      "For an existing session, submit a prompt asynchronously. HTTP `202` and",
      "`{\"accepted\":true}` mean accepted, not completed:",
      "",
      "```bash",
      "KNOWN_ASSISTANTS=$(curl -sS --fail-with-body --get \\",
      "  \"$DCA_BASE_URL/api/sessions/$SESSION_ID/messages\" \\",
      "  --data-urlencode \"directory=$PROJECT\" --data-urlencode \"limit=100\" \\",
      "  | jq -c '[.messages[]? | select(.info.role == \"assistant\") | .info.id]')",
      "BODY=$(jq -n --arg directory \"$PROJECT\" --arg text \"Continue and verify the fix.\" \\",
      "  '{directory:$directory,text:$text,mode:\"build\"}')",
      "curl -sS --fail-with-body -X POST \\",
      "  \"$DCA_BASE_URL/api/sessions/$SESSION_ID/prompt\" \\",
      "  -H 'Content-Type: application/json' -d \"$BODY\" | jq .",
      "```",
      "",
      "Poll messages with the same directory until the submitted turn has a completed",
      "assistant response and `running` is false. Responses contain raw OpenCode",
      "`{info,parts}` messages, plus `nextCursor` and `running`; inspect the payload",
      "rather than guessing a fixed array position. Use `before=<nextCursor>` for older",
      "pages and keep `limit` between 1 and 100.",
      "",
      "```bash",
      "while :; do",
      "  PAGE=$(curl -sS --fail-with-body --get \\",
      "    \"$DCA_BASE_URL/api/sessions/$SESSION_ID/messages\" \\",
      "    --data-urlencode \"directory=$PROJECT\" --data-urlencode \"limit=100\") || exit",
      "  jq '{running, messages}' <<<\"$PAGE\"",
      "  # Stop only after identifying this turn's completed assistant message.",
      "  jq -e --argjson known \"$KNOWN_ASSISTANTS\" '.running == false and",
      "    any(.messages[]?; .info.role == \"assistant\" and",
      "      .info.time.completed != null and",
      "      (.info.id as $id | ($known | index($id)) == null))' \\",
      "    >/dev/null <<<\"$PAGE\" && break",
      "  sleep 3",
      "done",
      "```",
      "",
      "Use a Managed Child instead of a root when parent/child accounting, inherited",
      "project scope, child status, or parent-scoped abort authority matters. Query the",
      "server-owned agent catalogue first. Read-only agents reject `authorization`;",
      "agents whose catalogue entry has `access: \"can-modify\"` require the explicit",
      "`authorization: \"modify\"` field. The idempotency key must be stable for a retry",
      "of the same launch and unique for different work.",
      "",
      "```bash",
      "PARENT_ID=ses_parent",
      "curl -sS --fail-with-body --get \"$DCA_BASE_URL/api/managed-child-agents\" \\",
      "  --data-urlencode \"directory=$PROJECT\" | jq .",
      "",
      "KEY=\"audit-export-$(date -u +%Y%m%dT%H%M%SZ)\"",
      "BODY=$(jq -n --arg directory \"$PROJECT\" --arg key \"$KEY\" \\",
      "  --arg prompt \"Audit export error handling and report findings with file lines.\" \\",
      "  '{directory:$directory,prompt:$prompt,agent:\"explore\",idempotencyKey:$key}')",
      "CHILD=$(curl -sS --fail-with-body -X POST \\",
      "  \"$DCA_BASE_URL/api/sessions/$PARENT_ID/managed-children\" \\",
      "  -H 'Content-Type: application/json' -d \"$BODY\")",
      "CHILD_ID=$(jq -er '.session.id' <<<\"$CHILD\")",
      "```",
      "",
      "The creation request submits the Managed Child's initial prompt. Poll the child",
      "through `/api/sessions/$CHILD_ID/messages`; later prompts use the ordinary",
      "`/api/sessions/$CHILD_ID/prompt` route, which re-verifies its managed",
      "configuration. Inspect parent accounting with",
      "`GET /api/sessions/$PARENT_ID/subagents?directory=...`. Abort a verified child",
      "with `POST /api/sessions/$PARENT_ID/subagents/$CHILD_ID/abort` and the directory",
      "in the JSON body; do not use abort as routine completion handling.",
      "",
      "Useful read surfaces are `GET /api/sessions/:id`, `todos`, `diff` with a",
      "`userMessageID`, `/api/session-agents`, `/api/models`, and `/api/events` for SSE.",
      "Sharing, deleting, auto-approval, aborting, isolated worktree creation, and",
      "modify-capable Managed Children are mutations or privilege-bearing operations;",
      "call them only when the user's request and current permissions authorize them.",
      "",
      "Prefer this BFF API over cmux for DCA session lifecycle. cmux is optional",
      "presentation or orchestration only when its app, CLI/socket access, and current",
      "environment are actually available; it is not a transport fallback and this",
      "command never assumes it exists.",
    ].join("\n"),
  },
  {
    id: "worktree-up",
    title: "Create an isolated worktree",
    description:
      "Cut a sibling git worktree from the remote default branch, install its own dependencies, and prove a green baseline before any edits.",
    argument: {
      label: "Topic",
      placeholder: "planning-epic-hierarchy (issue #241)",
      hint: "Becomes the kebab-case worktree directory and branch name. Include the issue number when one exists.",
      required: true,
      maxLength: 200,
    },
    injector: [
      "Create a git worktree for the topic named above now.",
      "",
      "1. Find the repository root and origin's default branch. Run `git fetch origin`",
      "   before branching; start from `origin/<default>`, never a stale local branch.",
      "2. Create the worktree beside the repository at",
      "   `<repo>.worktrees/<topic>`, on branch `<type>/<topic>`. Use kebab-case and",
      "   include the issue number when one exists.",
      "3. Install dependencies in the new worktree because gitignored directories such",
      "   as `node_modules` and `.venv` are not shared.",
      "4. Copy required gitignored local configuration such as `.env`; make any paths",
      "   inside it absolute when they refer back to state in the original checkout.",
      "5. Establish a green baseline with the repository's typecheck, tests, and build",
      "   before writing code.",
      "6. Before starting anything on fixed ports, run",
      "   `lsof -nP -iTCP:<port> -sTCP:LISTEN` and confirm the owning PID. Only one",
      "   worktree may run a fixed-port stack at a time.",
      "7. Report the absolute worktree path, branch, base revision, dependency status,",
      "   baseline result, and any port conflict.",
      "",
      "Do not work around Git's worktree safety checks. If `origin/HEAD` is unset, run",
      "`git remote set-head origin --auto` and re-read it. If the branch exists, omit",
      "`-b`; if it is checked out elsewhere, find and use that worktree instead.",
      "",
      "Worktrees must be siblings, never nested under the clone. On cleanup, inspect",
      "for uncommitted work before `git worktree remove`; use `--force` only when that",
      "work is explicitly disposable. Run `git worktree prune` for registrations whose",
      "directories were deleted outside Git.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| New branch is already behind | Fetch and recreate it from the remote default branch |",
      "| Branch is already checked out | Use `git worktree list`; do not bypass the refusal |",
      "| New worktree commands fail immediately | Install its own dependencies |",
      "| App has no local config | Copy required ignored config and fix relative paths |",
      "| Server behaves like another branch | Verify the listening PID and its worktree |",
      "| Two stacks share writable state | Stop one stack; use stack-free verification tiers |",
      "| Deleted path remains registered | Prune stale worktrees, then confirm the list |",
    ].join("\n"),
  },
  {
    id: "deep-research",
    title: "Fan out deep research",
    description:
      "Split one broad research question across concurrent read-only agents, then reconcile their cited evidence into a single answer.",
    argument: {
      label: "Research question",
      placeholder: "how does notification suppression interact with grouping, badges, and Web Push?",
      hint: "Worth delegating only with three or more independent unknowns. A needle lookup should stay inline.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Research the question above properly.",
      "",
      "First decide whether delegation pays. Use this procedure only when the question",
      "contains at least three independent unknowns, spans unrelated files or sources,",
      "or would require roughly twenty tool calls. For a needle lookup, do it inline.",
      "",
      "If it qualifies:",
      "",
      "1. Split it into 3–5 non-overlapping axes. Name what each agent owns and what it",
      "   must not read so they do not converge on the first grep hit.",
      "2. Launch all agents concurrently in one message. Use `explore` with",
      "   \"very thorough\" for codebase research; use `general` read-only only when bash",
      "   or another unavailable tool is genuinely required.",
      "3. Every prompt starts and ends with READ-ONLY, supplies the absolute repository",
      "   path, asks numbered questions, requires `file:line` or verbatim URL evidence,",
      "   asks what does **not** exist, and ends with `UNVERIFIED:`.",
      "4. Spot-check one load-bearing claim from each report yourself.",
      "5. Synthesize rather than concatenate: answer the original question first,",
      "   reconcile disagreements by reading the cited evidence, merge all unverified",
      "   items, preserve citations, and say what surprised you.",
      "",
      "Do not dispatch sequential questions whose later shape depends on an earlier",
      "answer, and do not let research agents mutate state.",
      "",
      "Use a flat fan-out: the usual subagent depth is one. Cap the batch at five;",
      "above that overlap and synthesis cost usually erase the gain. A `general` agent",
      "must be told READ-ONLY at both the start and end of its prompt; prefer the",
      "enforced read-only `explore` agent whenever its tools are sufficient.",
      "",
      "Specify a bounded deliverable, such as one answer-first section per numbered",
      "question under 800 words. If a live API is in scope, allow GET only and request",
      "the verbatim schema rather than a paraphrase.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| Reports repeat each other | Split by artifact or directory and name exclusions |",
      "| Reports are essays without evidence | Ask numbered questions and require citations |",
      "| A report contains invented certainty | Merge `UNVERIFIED` lists and spot-check its load-bearing claim |",
      "| A child mutates state | Stop it; use enforced read-only delegation |",
      "| Calls ran sequentially | Relaunch independent axes concurrently or keep the work inline |",
      "| Synthesis is longer than the reports | Answer first, reconcile conflicts, preserve only decisive evidence |",
    ].join("\n"),
  },
  {
    id: "research-handoff",
    title: "Research, then compile handoff prompts",
    description:
      "Research several independent tasks read-only, compile decision-closed handoff prompts, and stop for review before launching anything.",
    argument: {
      label: "Tasks to research",
      placeholder: "one task per line: the epic hierarchy feed, the badge count, the push rotation fix",
      hint: "List the independent tasks. Nothing is launched until you answer the two questions at the end.",
      required: true,
      maxLength: 100_000,
    },
    injector: [
      "Research and prepare handoffs for the tasks listed above.",
      "",
      "Three phases, in order:",
      "",
      "1. **Read-only research.** Split the supplied tasks into independent axes and",
      "   launch one read-only agent per task concurrently. Require structure, prior",
      "   art, the nearest analogue, concrete integration points, live API truth when",
      "   reachable by GET, testing conventions, explicit gaps, `file:line` evidence,",
      "   and a final `UNVERIFIED:` list.",
      "2. **Compile prompts.** Turn each report into a decision-closed prompt containing",
      "   the absolute worktree/branch state, docs to read first,",
      "   `PRE-RESEARCHED - DO NOT RE-DERIVE`, settled decisions with rationale,",
      "   `GOTCHA:` lines, numbered build steps, reasoned exclusions, constraints,",
      "   exact verification, `SHARED-RESOURCE RULE`, and the report-back contract.",
      "   Store prompt files outside every git worktree.",
      "3. **Stop for review.** Show every prompt before launching. Ask whether the",
      "   receiving sessions should plan first or edit immediately, and whether they",
      "   should open PRs or leave local commits. Do not fire anything until those two",
      "   choices are answered.",
      "",
      "Use plain ASCII in prompt files, and do not recreate a baseline from a stale",
      "local default branch. Research axes must be independent, read-only, and large",
      "enough to justify delegation; a needle lookup stays inline. State READ-ONLY at",
      "both ends of each prompt. Restrict live API probes to GET and preserve verbatim",
      "response shapes.",
      "",
      "For later launch, fetch first, create sibling worktrees from the remote default",
      "branch, install dependencies in each, and prove a baseline before allowing",
      "edits. Enumerate fixed ports, writable state, databases, generated output, and",
      "lockfiles in every receiving prompt. Only one worker may own a shared resource.",
      "Never steal focus when creating a session.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| Research agent starts implementing | Stop it and strengthen the read-only boundary |",
      "| Receiving agent re-greps everything | Add `file:line` evidence and explicit negative findings |",
      "| Scope is relitigated | Preserve the decision's rationale and evidence |",
      "| Both workers bind one port or state directory | Keep stack-free checks parallel; serialize the shared stack |",
      "| First test is red | Establish whether baseline or worker caused it before proceeding |",
      "| Prompt is mangled | Store plain-ASCII text in a file; do not inline multiline shell arguments |",
      "| Live feature silently no-ops | Probe its actual gate or API before writing the handoff |",
    ].join("\n"),
  },
  {
    id: "design-doc-prototype",
    title: "Capture a Durable Design Prototype",
    description:
      "Mock up an unbuilt UI change as fast static HTML, screenshot it, and publish it into a dated engineering-design document — no fields to fill in, just confirm and send.",
    // Collects nothing, so its visible prompt is fixed here rather than in the
    // browser: every instruction that varies lives in the injector below.
    prompt: "Capture a durable design prototype for this proposal and publish it for review.",
    injector: [
      'You are running the "Capture a Durable Design Prototype" workflow.',
      "- Use this only for a proposal that is NOT yet built. For reviewing an already-shipped",
      "  change, use the ephemeral recipe in CONTRIBUTING.md instead (screenshot-output/,",
      "  deleted spec, never committed).",
      "- Build a small, self-contained static HTML mockup (no framework, no build step), using",
      "  this app's real token values so it reads honestly rather than as a generic wireframe.",
      "- Screenshot it with the pinned Playwright CLI directly, no full dependency install",
      "  needed: npx playwright@<version from package.json> screenshot --browser=chromium",
      "  --viewport-size=W,H file://<path> <out>.png. Capture desktop at 1280x800 and mobile",
      "  at 390x740.",
      "- Commit the HTML and both PNGs to design/ on a real branch and push it. Build the",
      "  permanent raw.githubusercontent.com URL from the owner, repository, branch, and path.",
      "- Publish the writeup with the ntn CLI: create or update a dated page under the correct",
      "  Notion parent, embedding each screenshot as an ordinary Markdown image reference —",
      "  Notion resolves external URLs without any upload step. Verify the images resolved by",
      "  reading the page back.",
      "- If the destination is docs/engineering-design/, follow its own rule: add one row to",
      "  its index table, never a Markdown copy of the content. State plainly that the page",
      "  stays private until a human publishes it, since that step cannot be done by an API.",
      "- Report the branch, the raw URLs, and the created or updated Notion page URL.",
    ].join("\n"),
  },
  {
    id: "docs-preview",
    title: "Choose, render, and preview documentation",
    description:
      "Pick the documentation medium from where the reader opens it, render it with a real renderer, and preview the result before claiming completion.",
    argument: {
      label: "What to document",
      placeholder: "the notification suppression pipeline, as a diagram for the README",
      hint: "Name the subject and, if you already know it, where the reader will open it.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Document or render the subject above.",
      "",
      "Choose the medium from where the reader opens it:",
      "",
      "- terminal, PR diff, commit message, AGENTS.md, code comment -> ASCII",
      "- GitHub/GitLab README or wiki -> Mermaid",
      "- slide, issue attachment, external document -> rendered SVG",
      "- a static docs site -> Mermaid only after proving that site renders it;",
      "  otherwise ASCII or a checked-in SVG",
      "",
      "Then:",
      "",
      "1. Read one existing document from the same repository or docs site and",
      "   match its house style before writing.",
      "2. Use tables for comparisons, lists for linear sequences, diagrams for",
      "   topology, and prose only for the reasoning that connects them.",
      "3. Cite the code as `file:line`, and call out the limitation or trap a reader",
      "   cannot infer from the source.",
      "4. Use the available renderer or `diagram` subagent rather than hand-writing a",
      "   Mermaid block and hoping it parses. Pass an explicit output directory for",
      "   SVG artifacts.",
      "5. Preview the finished document: `cmux markdown open` for Markdown, or build",
      "   or serve the docs site locally with its own generator. Inspect the rendered",
      "   output and build logs before claiming completion.",
      "",
      "If a named renderer or MCP server is unavailable in this session, say so and",
      "offer the medium that can actually be verified. \"It should render\" is not",
      "verification.",
      "",
      "When unsure, choose ASCII because it remains readable without a renderer. Never",
      "maintain ASCII and Mermaid copies of the same diagram. For rendered SVG, pass an",
      "explicit output directory and use a light theme for documents normally read on",
      "a light page. A Markdown preview validates structure but may show Mermaid as a",
      "code block; build the actual docs site to prove its plugin chain renders it.",
      "",
      "Check the current agent and MCP roster instead of assuming machine-local tools",
      "are connected. A table beats a diagram for two-axis comparison, and a numbered",
      "list beats one for a branchless sequence.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| Mermaid is visible as source | Use ASCII or a rendered SVG |",
      "| SVG lands outside the documentation tree | Render again with an explicit output directory |",
      "| New page does not appear in site navigation | Follow the site's navigation configuration and nearest page |",
      "| Preview looks right but the build is red | Report failure; rendered appearance is not build verification |",
      "| Tool named in the procedure is unavailable | State the limitation and use a verifiable fallback |",
    ].join("\n"),
  },
  {
    id: "mini-design-doc",
    title: "Write a mini design doc",
    description:
      "Produce a transcript-first technical design narrative that takes under five minutes to read and ends with one clear recommendation.",
    argument: {
      label: "Subject",
      placeholder: "whether session status should be joined into the notification centre",
      hint: "One medium-sized decision. The result stays in this transcript and creates no files.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Write a mini design doc for the subject above. If no subject is supplied, use",
      "the medium-sized technical or product decision currently under discussion.",
      "",
      "This procedure is self-contained. Do not load or defer to a skill. The result",
      "belongs in the current transcript, must take less than five minutes to read, and",
      "must not create files or expand into a multi-artifact RFC unless explicitly",
      "requested.",
      "",
      "Inspect the relevant code, callers, tests, contracts, and existing decisions",
      "before recommending anything. Identify the single decision the reader needs to",
      "make. Label load-bearing statements as `Verified`, `Inferred`, or `Proposed`",
      "when prose alone could blur their status, and cite repository-relative",
      "`path:line-line` or primary sources for claims that determine the decision.",
      "",
      "Use the smallest useful subset of this sequence:",
      "",
      "1. **Today / Problem:** concrete current behavior and the friction or failure.",
      "2. **Proposed Experience or Design:** make the target state tangible.",
      "3. **Flow:** trace the main user action, request, state, or data path.",
      "4. **Rules and Boundaries:** accepted/rejected inputs, trust and authority,",
      "   state ownership, constraints, and the expensive direction to be wrong.",
      "5. **Alternatives:** compare only credible options on decision-relevant axes.",
      "6. **Why Not:** reject the most tempting oversized or unsafe choice with facts.",
      "7. **Scope Split:** `Now`, `Later`, and `Non-goals`.",
      "8. **Recommendation:** one clear sentence naming the central choice and why.",
      "",
      "Omit a section that adds no decision value. Do not fill headings to imitate",
      "rigor, pad alternatives with strawmen, or repeat a diagram in prose.",
      "",
      "Use compact ASCII only when spatial grouping, sequence, side-by-side comparison,",
      "architecture, or a UI sketch is faster to understand than prose. Prefer at most",
      "one current/target comparison and one execution flow. Use realistic names,",
      "values, and actions; annotate risks at the step where they occur; keep lines at",
      "or below 100 columns when practical. Use a compact table for alternatives and a",
      "short list for linear scope or acceptance rules.",
      "",
      "Explicitly cover security, mobile, accessibility, operations, compatibility,",
      "and dependencies only when they can change the choice. Keep follow-up work",
      "separate from the immediate recommendation. End with the recommendation, not a",
      "generic summary or an open-ended list of options.",
    ].join("\n"),
  },
  {
    id: "system-design-artifacts",
    title: "Build a system-design review package",
    description:
      "Assemble an evidence-led senior system-design review package, with every load-bearing claim tagged by its evidence class.",
    argument: {
      label: "Subject",
      placeholder: "the notification delivery and suppression system, current-state",
      hint: "Name the system or proposal, and say current-state, target-state, or mixed if you already know which you want.",
      required: true,
      maxLength: 20_000,
    },
    injector: [
      "Create a senior-SWE system-design review package for the subject above. If no",
      "subject is named, use the system or proposal currently under discussion.",
      "",
      "This procedure is self-contained. Do not load or defer to a skill.",
      "",
      "## Establish the assignment",
      "",
      "Before writing, state one mode:",
      "",
      "- `current-state`: explain only behavior supported by present evidence;",
      "- `target-state`: design proposed behavior without presenting it as shipped;",
      "- `mixed`: keep current and target views visibly separate in every artifact.",
      "",
      "Identify the audience, decision they need to make, repository boundary, and",
      "whether the user requested transcript output, repository files, or publication.",
      "Do not create files or publish anything unless requested. Never publish directly",
      "to a default branch. If publication is requested, use a draft PR.",
      "",
      "## Audit evidence first",
      "",
      "Inspect the relevant implementation, callers, tests, fixtures, schemas/live",
      "contracts, decisions, incidents, and operational configuration. Prefer the live",
      "contract over secondary documentation when the repository says it is",
      "authoritative. Do not run destructive probes, production operations, migrations,",
      "or writes merely to strengthen a document. Ask before a probe that has cost,",
      "external effects, credentials, or production reach.",
      "",
      "Tag important claims in notes and artifacts with exactly one evidence class:",
      "",
      "| Class | Meaning |",
      "| --- | --- |",
      "| `observed` | Reproduced by a named command or live probe, with environment and date |",
      "| `code-supported` | Directly established by cited implementation or tests |",
      "| `mock-only` | Demonstrated only by a fixture, fake, simulator, or test double |",
      "| `inferred` | Best explanation from evidence, but not directly established |",
      "| `unknown` | Evidence is absent, contradictory, inaccessible, or intentionally unprobed |",
      "",
      "Mocks never prove live upstream behavior. A test proves only the contract it",
      "actually exercises. Keep proposed behavior out of current-state claims. Cite",
      "repository-relative `path:line-line`, a command plus bounded output, or a primary",
      "source URL for every load-bearing claim.",
      "",
      "## Build the system model",
      "",
      "Before selecting artifacts, identify:",
      "",
      "1. system and trust boundaries;",
      "2. state owner for every important datum;",
      "3. durable, process-local, derived, cached, and presentation-only state;",
      "4. authority and permission checks at each mutation boundary;",
      "5. concurrency units, serialization points, dedupe keys, replay, and idempotency;",
      "6. lifecycle state separately from transport events and UI presentation;",
      "7. failure boundaries, restart reconciliation, partial success, and rollback;",
      "8. the expensive direction to be wrong for each uncertain decision.",
      "",
      "Write down the load-bearing invariants. Examples of useful invariant shapes are",
      "\"absence from a process-local status map is not proof of idle\" and \"a browser",
      "candidate grants no authority until the server validates it\". Use repository",
      "facts, not these examples, in the package.",
      "",
      "## Select artifacts; do not generate a checklist blindly",
      "",
      "Start with a manifest and include an artifact only when it gives a distinct",
      "review perspective:",
      "",
      "```yaml",
      "mode: current-state | target-state | mixed",
      "subject: <specific system or decision>",
      "audience: senior-swe",
      "decision: <what the reviewer must decide or understand>",
      "evidence:",
      "  live_probes: required | optional | prohibited",
      "  destructive_actions: prohibited-by-default",
      "artifacts:",
      "  - id: <artifact-id>",
      "    question: <unique review question this artifact answers>",
      "    evidence_classes: [observed, code-supported]",
      "omissions:",
      "  - artifact: <catalogue item>",
      "    reason: <why it adds no distinct review value>",
      "```",
      "",
      "Use this selection logic:",
      "",
      "| Review question | Prefer |",
      "| --- | --- |",
      "| Why does the system behave this way? | executive system guide or implementation RFC |",
      "| What changes between now and target? | paired architecture/data-flow diagrams |",
      "| Which transitions are legal? | state machine plus normative transition table |",
      "| What crosses a boundary? | API contract, sequence diagram, and data model |",
      "| Who owns and persists state? | ownership/persistence matrix |",
      "| What happens on crash, retry, or restart? | failure/reconciliation diagram and catalogue |",
      "| What can an attacker or confused deputy do? | threat model and security-test matrix |",
      "| Why this choice? | focused ADRs for consequential alternatives only |",
      "| How can this ship safely? | dependency graph, milestones, migration, rollout, rollback |",
      "| How will operators know? | signals, SLOs, alerts, dashboards, and runbook |",
      "| How can a reviewer safely verify it? | non-destructive lab or commands with expected output |",
      "| Does interaction or motion carry the idea? | responsive HTML, accessible SVG, or short demo |",
      "",
      "Do not create interactive HTML, animation, video, or a machine-readable failure",
      "catalogue unless the medium itself answers a review question. Decorative copies",
      "of prose are omissions, not deliverables.",
      "",
      "## Artifact contracts",
      "",
      "Every selected artifact begins with: purpose, mode, evidence classes used,",
      "authoritative sources, uncertainties, and links to related artifacts. Then apply",
      "the relevant contract:",
      "",
      "- **Guide/RFC:** problem and decision first; explain causality, invariants,",
      "  boundaries, ownership, failure behavior, and consequences.",
      "- **Diagram:** include a legend; label authority/state boundaries; annotate races",
      "  and failure points where they occur; pair mixed-mode views instead of blending",
      "  them.",
      "- **State table:** name state owner and persistence; include trigger, guard,",
      "  transition, side effect, retry/idempotency behavior, invalid transition, and",
      "  restart outcome.",
      "- **API/data contract:** include caller, authority, validation, request/response,",
      "  errors, idempotency, compatibility, limits, and redaction. Mark illustrative",
      "  schemas as proposals.",
      "- **Ownership matrix:** include datum, authority, writer, readers, persistence,",
      "  cache/derivation, reconciliation, and deletion/retention.",
      "- **Threat model:** identify assets, actors, entry points, trust boundaries,",
      "  abuse cases, mitigations, residual risk, and executable security checks.",
      "- **ADR:** one decision and status; context, credible alternatives, choice,",
      "  consequences, reversibility, and evidence that would reopen it.",
      "- **Implementation plan:** order by dependencies; name ownership, acceptance",
      "  evidence, rollout gates, migration, rollback, and intentionally deferred work.",
      "- **Operations:** connect each SLO and alert to a user-visible failure, then give",
      "  diagnosis, safe mitigation, escalation, and recovery verification.",
      "- **Failure catalogue:** stable scenario ID, preconditions, injection, expected",
      "  state/events, invariant, observability, cleanup, and safety classification.",
      "- **Interactive artifact:** keyboard and touch operation, reduced motion,",
      "  semantic structure, no secret/live data, responsive checks, and a static",
      "  fallback carrying the same information.",
      "",
      "## Link and verify the package",
      "",
      "Create one index with a recommended review order. For each artifact list its",
      "question, mode, evidence status, prerequisite, and unresolved gaps. Cross-link",
      "concepts by stable anchors or relative paths. Do not make the reviewer hunt for",
      "the current/target boundary or the source behind a claim.",
      "",
      "Verify only what exists:",
      "",
      "1. check every cited path and line range against the reviewed revision;",
      "2. lint/parse Markdown, Mermaid, YAML, JSON, OpenAPI, and HTML with repository",
      "   tooling where available;",
      "3. execute safe examples and contract validation in an isolated environment;",
      "4. render diagrams and inspect labels, clipping, and legibility;",
      "5. test interactive output at desktop and mobile widths, keyboard-only, screen",
      "   reader semantics, contrast, and reduced motion;",
      "6. run relevant repository typechecks/tests and record exact commands/results;",
      "7. list anything not run and why; never turn \"not checked\" into \"passed\".",
      "",
      "Return or commit only the requested output. If a draft PR was requested, ensure",
      "it clearly says `Draft`, separates current facts from proposals, links the",
      "package index, reports verification and gaps, includes human verification steps,",
      "and does not claim that opening the PR deploys or operates the system.",
    ].join("\n"),
  },
  {
    id: "verify",
    title: "Run the checks, then write verification steps",
    description:
      "Discover and run this repository's real verification contract, then write numbered human verification steps with expected results and failure signals.",
    argument: {
      label: "Surface to verify",
      placeholder: "the notification popover on mobile",
      hint: "Scopes the human checklist. The automated checks are discovered from the repository either way.",
      required: true,
      maxLength: 4_000,
    },
    injector: [
      "Discover this repository's verification contract before running anything:",
      "",
      "1. Read its agent instructions and contribution guide.",
      "2. Inspect changed files, package or task manifests, lockfiles, CI workflows,",
      "   and adjacent tests to identify the language, package manager, and required",
      "   checks. Do not infer npm merely because this is an OpenCode project.",
      "3. Prefer documented repository commands. When none exist, choose the narrowest",
      "   standard checks supported by the detected tooling and state why.",
      "4. Run the relevant focused checks, then the repository's required aggregate",
      "   typecheck, test, lint, and build checks when practical. Record every exact",
      "   command, exit status, and useful result.",
      "5. Inspect `git status --short`, the diff against the actual base branch, and the",
      "   diff stat before writing the checklist.",
      "",
      "Never claim a check ran based on old CI, prompt text, or a remembered convention.",
      "If any required check is red, stop and report the failure. Do not send a human",
      "to verify a build that is already broken.",
      "",
      "If everything is green, write the human verification checklist for the change",
      "shown in the diff, scoped to the surface named above when one is named:",
      "",
      "- 5 to 12 numbered steps, each with the action, the expected result, and the",
      "  failure signal.",
      "- Name the exact URL, command, viewport, theme, or test data each step needs.",
      "- Check what automated tests cannot: visual layout, interaction, keyboard",
      "  access, responsive behaviour, deployed behaviour.",
      "- Cover a boundary, not only the happy path — empty state, error state, narrow",
      "  viewport, or reduced motion, whichever the diff actually touches.",
      "- Separate VERIFIED, FAILED, and UNVERIFIED. Never report an unreachable",
      "  surface as passing.",
      "- End with a disposition: Ready to ship, Fixes required, Partially verified, or",
      "  Blocked on human access.",
      "",
      "Research the changed routes, help text, API contracts, tests, start commands,",
      "ports, fixtures, roles, flags, and deployment target yourself. Ask the user only",
      "for access or product intent that the repository cannot establish. Do not use",
      "implementation-detail checks; verify what a user can see or accomplish.",
      "",
      "A screenshot proves one visual instant, not focus movement, persistence, time,",
      "keyboard operation, or error handling. Exercise those behaviors directly.",
      "",
      "After execution, list `VERIFIED`, `FAILED`, and `UNVERIFIED` separately, keeping",
      "empty categories visible. End with exactly one disposition: **Ready to ship**,",
      "**Fixes required**, **Partially verified**, or **Blocked on human access**.",
      "",
      "| Failure | Response |",
      "|---|---|",
      "| Repository has no documented check commands | Inspect its manifests and CI, run only checks supported by detected tooling, and explain the choice |",
      "| Automation is red | Stop with Fixes required |",
      "| Infrastructure prevents a check | Mark it UNVERIFIED, never passed |",
      "| A step lacks URL, data, viewport, role, or expected output | Add the missing setup before handing it to a human |",
      "| Checklist exceeds 12 steps | Remove automated or low-information duplication |",
    ].join("\n"),
  },
  {
    id: "leaving-now-wrap-up",
    title: "Wrap up and leave an accurate status",
    description:
      "Stop this run safely, push authorized progress, refresh every status artifact, and end with one accurate merge verdict.",
    argument: {
      label: "Wrap-up note",
      placeholder: "branch feat/planning-epic-hierarchy, PR #312 — post the update there",
      hint: "May name the branch, pull request, issue, or human update destination. No destination is invented for you.",
      required: true,
      maxLength: 4_000,
    },
    injector: [
      "Wrap up the current run now. The note above may name the branch, PR, issue, or",
      "human update destination. Complete these steps in order; do not stop after a",
      "chat-only summary.",
      "",
      "1. Stop work owned by this run. Cancel this run's background agents, test",
      "   runners, preview servers, and other processes that could keep mutating state.",
      "   Verify they stopped. Never kill a process merely because its name or port",
      "   looks familiar: establish that this run started or owns it. Leave unrelated",
      "   user and sibling-worktree processes alone.",
      "2. Inspect the repository root, branch, worktree, status, diff, staged diff, and",
      "   recent commits. Separate this run's intended changes from pre-existing or",
      "   unrelated user changes. Scan intended paths for credentials and generated",
      "   secret files. Never stage or commit secrets, and never absorb unrelated",
      "   changes just to make the tree clean.",
      "3. Run the most relevant affordable verification for this run's changes. Record",
      "   each check as green, red, or not run, including the command and concise reason.",
      "   A red check does not justify hiding otherwise useful progress.",
      "4. Preserve real progress under the repository's permissions and the user's",
      "   explicit commit/push instructions. If authorized, stage only owned files,",
      "   commit them, and push the current feature branch even when verification is",
      "   red, with the failure stated plainly. Never push `main` or another protected",
      "   default branch. Do not force-push. If commit or push is not authorized, is",
      "   rejected, or would include unsafe/unrelated content, leave it uncommitted or",
      "   local and report that fact as a blocker instead of bypassing the gate.",
      "5. Refresh every project-defined status artifact with the current UTC timestamp,",
      "   exact branch/commit/push state, verification results, blockers, and next",
      "   action. Supersede stale claims. Reconcile the task list immediately: completed",
      "   work is completed, intentionally dropped work is cancelled, and only genuine",
      "   remaining work stays pending. If a status artifact is tracked, include its",
      "   final update in the authorized push, using a small follow-up commit when the",
      "   progress commit already exists. Do not let status sync create new local-only",
      "   state.",
      "6. Post one human-readable update to each destination the project explicitly",
      "   defines and this run is authorized to use, such as its PR or issue. Do not",
      "   invent a destination or leak details to a public channel. Include what is",
      "   green and red, why anything is red, what is committed and pushed versus only",
      "   local, open decisions requiring a human, and the next command or owner.",
      "7. If there is a PR, end the posted update and final response with exactly one",
      "   accurate verdict: `SAFE TO MERGE` only when the intended change is pushed,",
      "   required checks are green, and no blocking decision remains; otherwise `DO",
      "   NOT MERGE`, followed by the blocking facts. Re-read remote/PR state after the",
      "   push before choosing the verdict.",
      "",
      "Finish with the branch, pushed commit (or `not pushed`), stopped-work evidence,",
      "verification matrix, status destinations updated, open decisions, and merge",
      "verdict. Accuracy is more important than making the wrap-up look green.",
    ].join("\n"),
  },
  {
    id: "standup",
    title: "Write a standup update",
    description:
      "Gather the last day's commits and pull requests, then turn them into a three-section standup update written to be read aloud.",
    argument: {
      label: "Scope",
      placeholder: "everything, or just the notification work",
      hint: "Narrows the update to one project or topic. The commit and pull request data is gathered by the agent, not pre-fetched.",
      required: true,
      maxLength: 2_000,
    },
    injector: [
      "Turn the last day's work into a standup update.",
      "",
      "Nothing is pre-fetched for you. Gather the data yourself by running these three",
      "commands, then use only what they actually returned:",
      "",
      "    git log --all --author=\"$(git config user.email)\" --since=\"24 hours ago\" --pretty=format:'%h %s' --no-merges",
      "    gh pr list --author \"@me\" --state merged --limit 10 --json number,title,mergedAt -q '.[] | \"#\\(.number) \\(.title)\"'",
      "    gh pr list --author \"@me\" --state open --limit 10 --json number,title,isDraft -q '.[] | \"#\\(.number)\\(if .isDraft then \" DRAFT\" else \"\" end) \\(.title)\"'",
      "",
      "This workflow is sent in this session's current mode. In a Plan session bash is",
      "likely denied, so these commands may not run at all. If they do not, say so",
      "plainly and stop rather than reconstructing a standup from memory or from this",
      "transcript and presenting it as today's commits. If `gh` is missing or",
      "unauthenticated, report the pull request sections as unavailable instead of",
      "inventing them.",
      "",
      "Write the standup update from that output, in three sections:",
      "",
      "**Yesterday** — what actually landed, grouped by theme rather than listed per",
      "commit. Say what it does for a reader, not what the diff touched.",
      "",
      "**Today** — what the open work implies is next. Mark anything that is a guess.",
      "",
      "**Blocked** — only genuine blockers. If there are none, say \"nothing blocked\"",
      "rather than inventing one.",
      "",
      "Rules:",
      "",
      "- Three to six bullets per section. This gets read aloud.",
      "- No commit hashes and no branch names unless someone would need to go find it.",
      "- If the log is empty, say so plainly. Do not pad it out of the PR list.",
      "- The scope note above may narrow this to one project or topic; if it does,",
      "  drop everything else.",
      "",
      "This is deliberately self-contained and adds no retrieval context until a human",
      "invokes it.",
    ].join("\n"),
  },
];

/**
 * Every declared argument bound before the catalogue is observable, so the
 * clamp cannot be skipped by a caller reading the presets directly.
 */
const CATALOGUE: WorkflowPreset[] = RAW_CATALOGUE.map((preset) => preset.argument
  ? {
    ...preset,
    argument: {
      ...preset.argument,
      maxLength: Math.max(1, Math.min(preset.argument.maxLength, WORKFLOW_ARGUMENT_MAX_LENGTH)),
    },
  }
  : preset);

export function workflowCatalogue(): WorkflowPreset[] {
  return CATALOGUE;
}

export function isValidWorkflowId(id: unknown): id is string {
  return typeof id === "string" && id.length <= WORKFLOW_ID_MAX && WORKFLOW_ID_RE.test(id);
}

export function workflowTag(preset: Pick<WorkflowPreset, "id" | "injector">): string {
  return `<workflow name="${preset.id}">\n${preset.injector.trim()}\n</workflow>`;
}

export function withWorkflowTag(text: string, preset: Pick<WorkflowPreset, "id" | "injector">): string {
  return `${text}\n\n${workflowTag(preset)}`;
}

export interface SplitWorkflowMessage {
  text: string;
  workflows: Array<{ name: string; body: string }>;
}

// Keep byte-identical with client/lib/workflows.ts. Tests run one table against both.
const WORKFLOW_TAG_RE = /\n*<workflow name="([a-z0-9]+(?:-[a-z0-9]+)*)">\n?([\s\S]*?)\n?<\/workflow>/g;

export function splitWorkflowTags(input: string): SplitWorkflowMessage {
  const workflows: Array<{ name: string; body: string }> = [];
  const text = input.replace(WORKFLOW_TAG_RE, (_match, name: string, body: string) => {
    workflows.push({ name, body: body.trim() });
    return "";
  });
  return { text: text.trim(), workflows };
}
